# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uroven_4.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_uroven_4(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        MainWindow.setMinimumSize(QtCore.QSize(450, 500))
        MainWindow.setMaximumSize(QtCore.QSize(450, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_vosvrat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vosvrat.setObjectName("pushButton_vosvrat")
        self.verticalLayout.addWidget(self.pushButton_vosvrat)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_y4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_1.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_1.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_1.setObjectName("pushButton_y4_1")
        self.horizontalLayout.addWidget(self.pushButton_y4_1)
        self.pushButton_y4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_2.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_2.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_2.setObjectName("pushButton_y4_2")
        self.horizontalLayout.addWidget(self.pushButton_y4_2)
        self.pushButton_y4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_3.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_3.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_3.setObjectName("pushButton_y4_3")
        self.horizontalLayout.addWidget(self.pushButton_y4_3)
        self.pushButton_y4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_4.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_4.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_4.setObjectName("pushButton_y4_4")
        self.horizontalLayout.addWidget(self.pushButton_y4_4)
        self.pushButton_y4_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_5.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_5.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_5.setObjectName("pushButton_y4_5")
        self.horizontalLayout.addWidget(self.pushButton_y4_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_y4_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_6.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_6.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_6.setObjectName("pushButton_y4_6")
        self.horizontalLayout_2.addWidget(self.pushButton_y4_6)
        self.pushButton_y4_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_7.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_7.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_7.setObjectName("pushButton_y4_7")
        self.horizontalLayout_2.addWidget(self.pushButton_y4_7)
        self.pushButton_y4_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_8.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_8.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_8.setObjectName("pushButton_y4_8")
        self.horizontalLayout_2.addWidget(self.pushButton_y4_8)
        self.pushButton_y4_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_9.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_9.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_9.setObjectName("pushButton_y4_9")
        self.horizontalLayout_2.addWidget(self.pushButton_y4_9)
        self.pushButton_y4_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_10.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_10.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_10.setObjectName("pushButton_y4_10")
        self.horizontalLayout_2.addWidget(self.pushButton_y4_10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_y4_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_11.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_11.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_11.setObjectName("pushButton_y4_11")
        self.horizontalLayout_3.addWidget(self.pushButton_y4_11)
        self.pushButton_y4_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_12.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_12.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_12.setObjectName("pushButton_y4_12")
        self.horizontalLayout_3.addWidget(self.pushButton_y4_12)
        self.pushButton_y4_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_13.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_13.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_13.setObjectName("pushButton_y4_13")
        self.horizontalLayout_3.addWidget(self.pushButton_y4_13)
        self.pushButton_y4_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_14.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_14.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_14.setObjectName("pushButton_y4_14")
        self.horizontalLayout_3.addWidget(self.pushButton_y4_14)
        self.pushButton_y4_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_15.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_15.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_15.setObjectName("pushButton_y4_15")
        self.horizontalLayout_3.addWidget(self.pushButton_y4_15)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_y4_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_16.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_16.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_16.setObjectName("pushButton_y4_16")
        self.horizontalLayout_4.addWidget(self.pushButton_y4_16)
        self.pushButton_y4_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_17.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_17.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_17.setObjectName("pushButton_y4_17")
        self.horizontalLayout_4.addWidget(self.pushButton_y4_17)
        self.pushButton_y4_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_18.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_18.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_18.setObjectName("pushButton_y4_18")
        self.horizontalLayout_4.addWidget(self.pushButton_y4_18)
        self.pushButton_y4_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_19.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_19.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_19.setObjectName("pushButton_y4_19")
        self.horizontalLayout_4.addWidget(self.pushButton_y4_19)
        self.pushButton_y4_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_20.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_20.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_20.setObjectName("pushButton_y4_20")
        self.horizontalLayout_4.addWidget(self.pushButton_y4_20)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_y4_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_21.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_21.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_21.setObjectName("pushButton_y4_21")
        self.horizontalLayout_5.addWidget(self.pushButton_y4_21)
        self.pushButton_y4_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_22.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_22.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_22.setObjectName("pushButton_y4_22")
        self.horizontalLayout_5.addWidget(self.pushButton_y4_22)
        self.pushButton_y4_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_23.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_23.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_23.setObjectName("pushButton_y4_23")
        self.horizontalLayout_5.addWidget(self.pushButton_y4_23)
        self.pushButton_y4_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_24.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_24.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_24.setObjectName("pushButton_y4_24")
        self.horizontalLayout_5.addWidget(self.pushButton_y4_24)
        self.pushButton_y4_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y4_25.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_25.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y4_25.setObjectName("pushButton_y4_25")
        self.horizontalLayout_5.addWidget(self.pushButton_y4_25)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Уровень 4"))
        MainWindow.setWindowIcon(QtGui.QIcon('иконка.png'))
        self.pushButton_vosvrat.setText(_translate("MainWindow", "Вернуться назад"))
        self.pushButton_y4_1.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_2.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_3.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_4.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_5.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_6.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_7.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_8.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_9.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_10.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_11.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_12.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_13.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_14.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_15.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_16.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_17.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_18.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_19.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_20.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_21.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_22.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_23.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_24.setText(_translate("MainWindow", "X"))
        self.pushButton_y4_25.setText(_translate("MainWindow", "X"))

        self.pushButton_vosvrat.setStyleSheet('QPushButton {background-color: #EEE8AA;}')
        self.pushButton_y4_1.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_2.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_3.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_4.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_5.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_6.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_7.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_8.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_9.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_10.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_11.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_12.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_13.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_14.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_15.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_16.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_17.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_18.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_19.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_20.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_21.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_22.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_23.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_24.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y4_25.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')

