# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uroven_3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_uroven_3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        MainWindow.setMinimumSize(QtCore.QSize(450, 500))
        MainWindow.setMaximumSize(QtCore.QSize(450, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_vosvrat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vosvrat.setObjectName("pushButton_vosvrat")
        self.verticalLayout.addWidget(self.pushButton_vosvrat)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_y3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_1.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_1.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_1.setObjectName("pushButton_y3_1")
        self.horizontalLayout.addWidget(self.pushButton_y3_1)
        self.pushButton_y3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_2.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_2.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_2.setObjectName("pushButton_y3_2")
        self.horizontalLayout.addWidget(self.pushButton_y3_2)
        self.pushButton_y3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_3.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_3.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_3.setObjectName("pushButton_y3_3")
        self.horizontalLayout.addWidget(self.pushButton_y3_3)
        self.pushButton_y3_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_4.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_4.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_4.setObjectName("pushButton_y3_4")
        self.horizontalLayout.addWidget(self.pushButton_y3_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_y3_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_5.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_5.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_5.setObjectName("pushButton_y3_5")
        self.horizontalLayout_6.addWidget(self.pushButton_y3_5)
        self.pushButton_y3_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_6.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_6.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_6.setObjectName("pushButton_y3_6")
        self.horizontalLayout_6.addWidget(self.pushButton_y3_6)
        self.pushButton_y3_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_7.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_7.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_7.setObjectName("pushButton_y3_7")
        self.horizontalLayout_6.addWidget(self.pushButton_y3_7)
        self.pushButton_y3_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_8.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_8.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_8.setObjectName("pushButton_y3_8")
        self.horizontalLayout_6.addWidget(self.pushButton_y3_8)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_y3_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_9.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_9.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_9.setObjectName("pushButton_y3_9")
        self.horizontalLayout_7.addWidget(self.pushButton_y3_9)
        self.pushButton_y3_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_10.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_10.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_10.setObjectName("pushButton_y3_10")
        self.horizontalLayout_7.addWidget(self.pushButton_y3_10)
        self.pushButton_y3_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_11.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_11.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_11.setObjectName("pushButton_y3_11")
        self.horizontalLayout_7.addWidget(self.pushButton_y3_11)
        self.pushButton_y3_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_12.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_12.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_12.setObjectName("pushButton_y3_12")
        self.horizontalLayout_7.addWidget(self.pushButton_y3_12)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_y3_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_13.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_13.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_13.setObjectName("pushButton_y3_13")
        self.horizontalLayout_8.addWidget(self.pushButton_y3_13)
        self.pushButton_y3_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_14.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_14.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_14.setObjectName("pushButton_y3_14")
        self.horizontalLayout_8.addWidget(self.pushButton_y3_14)
        self.pushButton_y3_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_15.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_15.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_15.setObjectName("pushButton_y3_15")
        self.horizontalLayout_8.addWidget(self.pushButton_y3_15)
        self.pushButton_y3_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y3_16.setMinimumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_16.setMaximumSize(QtCore.QSize(70, 70))
        self.pushButton_y3_16.setObjectName("pushButton_y3_16")
        self.horizontalLayout_8.addWidget(self.pushButton_y3_16)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Уровень 3"))
        MainWindow.setWindowIcon(QtGui.QIcon('иконка.png'))
        self.pushButton_vosvrat.setText(_translate("MainWindow", "Вернуться назад"))
        self.pushButton_y3_1.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_2.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_3.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_4.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_5.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_6.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_7.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_8.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_9.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_10.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_11.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_12.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_13.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_14.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_15.setText(_translate("MainWindow", "X"))
        self.pushButton_y3_16.setText(_translate("MainWindow", "X"))

        self.pushButton_vosvrat.setStyleSheet('QPushButton {background-color: #EEE8AA;}')
        self.pushButton_y3_1.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_2.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_3.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_4.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_5.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_6.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_7.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_8.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_9.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_10.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_11.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_12.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_13.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_14.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_15.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y3_16.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')

