# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uroven_5.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_uroven_5(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        MainWindow.setMinimumSize(QtCore.QSize(450, 500))
        MainWindow.setMaximumSize(QtCore.QSize(450, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_vosvrat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vosvrat.setObjectName("pushButton_vosvrat")
        self.verticalLayout.addWidget(self.pushButton_vosvrat)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_y5_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_1.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_1.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_1.setObjectName("pushButton_y5_1")
        self.horizontalLayout_2.addWidget(self.pushButton_y5_1)
        self.pushButton_y5_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_2.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_2.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_2.setObjectName("pushButton_y5_2")
        self.horizontalLayout_2.addWidget(self.pushButton_y5_2)
        self.pushButton_y5_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_3.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_3.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_3.setObjectName("pushButton_y5_3")
        self.horizontalLayout_2.addWidget(self.pushButton_y5_3)
        self.pushButton_y5_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_4.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_4.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_4.setObjectName("pushButton_y5_4")
        self.horizontalLayout_2.addWidget(self.pushButton_y5_4)
        self.pushButton_y5_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_5.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_5.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_5.setObjectName("pushButton_y5_5")
        self.horizontalLayout_2.addWidget(self.pushButton_y5_5)
        self.pushButton_y5_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_6.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_6.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_6.setObjectName("pushButton_y5_6")
        self.horizontalLayout_2.addWidget(self.pushButton_y5_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_y5_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_7.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_7.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_7.setObjectName("pushButton_y5_7")
        self.horizontalLayout_3.addWidget(self.pushButton_y5_7)
        self.pushButton_y5_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_8.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_8.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_8.setObjectName("pushButton_y5_8")
        self.horizontalLayout_3.addWidget(self.pushButton_y5_8)
        self.pushButton_y5_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_9.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_9.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_9.setObjectName("pushButton_y5_9")
        self.horizontalLayout_3.addWidget(self.pushButton_y5_9)
        self.pushButton_y5_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_10.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_10.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_10.setObjectName("pushButton_y5_10")
        self.horizontalLayout_3.addWidget(self.pushButton_y5_10)
        self.pushButton_y5_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_11.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_11.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_11.setObjectName("pushButton_y5_11")
        self.horizontalLayout_3.addWidget(self.pushButton_y5_11)
        self.pushButton_y5_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_12.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_12.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_12.setObjectName("pushButton_y5_12")
        self.horizontalLayout_3.addWidget(self.pushButton_y5_12)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_y5_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_13.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_13.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_13.setObjectName("pushButton_y5_13")
        self.horizontalLayout_4.addWidget(self.pushButton_y5_13)
        self.pushButton_y5_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_14.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_14.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_14.setObjectName("pushButton_y5_14")
        self.horizontalLayout_4.addWidget(self.pushButton_y5_14)
        self.pushButton_y5_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_15.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_15.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_15.setObjectName("pushButton_y5_15")
        self.horizontalLayout_4.addWidget(self.pushButton_y5_15)
        self.pushButton_y5_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_16.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_16.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_16.setObjectName("pushButton_y5_16")
        self.horizontalLayout_4.addWidget(self.pushButton_y5_16)
        self.pushButton_y5_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_17.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_17.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_17.setObjectName("pushButton_y5_17")
        self.horizontalLayout_4.addWidget(self.pushButton_y5_17)
        self.pushButton_y5_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_18.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_18.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_18.setObjectName("pushButton_y5_18")
        self.horizontalLayout_4.addWidget(self.pushButton_y5_18)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_y5_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_19.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_19.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_19.setObjectName("pushButton_y5_19")
        self.horizontalLayout_6.addWidget(self.pushButton_y5_19)
        self.pushButton_y5_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_20.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_20.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_20.setObjectName("pushButton_y5_20")
        self.horizontalLayout_6.addWidget(self.pushButton_y5_20)
        self.pushButton_y5_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_21.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_21.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_21.setObjectName("pushButton_y5_21")
        self.horizontalLayout_6.addWidget(self.pushButton_y5_21)
        self.pushButton_y5_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_22.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_22.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_22.setObjectName("pushButton_y5_22")
        self.horizontalLayout_6.addWidget(self.pushButton_y5_22)
        self.pushButton_y5_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_23.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_23.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_23.setObjectName("pushButton_y5_23")
        self.horizontalLayout_6.addWidget(self.pushButton_y5_23)
        self.pushButton_y5_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_24.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_24.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_24.setObjectName("pushButton_y5_24")
        self.horizontalLayout_6.addWidget(self.pushButton_y5_24)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_y5_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_25.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_25.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_25.setObjectName("pushButton_y5_25")
        self.horizontalLayout_7.addWidget(self.pushButton_y5_25)
        self.pushButton_y5_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_26.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_26.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_26.setObjectName("pushButton_y5_26")
        self.horizontalLayout_7.addWidget(self.pushButton_y5_26)
        self.pushButton_y5_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_27.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_27.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_27.setObjectName("pushButton_y5_27")
        self.horizontalLayout_7.addWidget(self.pushButton_y5_27)
        self.pushButton_y5_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_28.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_28.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_28.setObjectName("pushButton_y5_28")
        self.horizontalLayout_7.addWidget(self.pushButton_y5_28)
        self.pushButton_y5_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_29.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_29.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_29.setObjectName("pushButton_y5_29")
        self.horizontalLayout_7.addWidget(self.pushButton_y5_29)
        self.pushButton_y5_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_30.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_30.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_30.setObjectName("pushButton_y5_30")
        self.horizontalLayout_7.addWidget(self.pushButton_y5_30)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_y5_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_31.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_31.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_31.setObjectName("pushButton_y5_31")
        self.horizontalLayout_8.addWidget(self.pushButton_y5_31)
        self.pushButton_y5_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_32.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_32.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_32.setObjectName("pushButton_y5_32")
        self.horizontalLayout_8.addWidget(self.pushButton_y5_32)
        self.pushButton_y5_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_33.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_33.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_33.setObjectName("pushButton_y5_33")
        self.horizontalLayout_8.addWidget(self.pushButton_y5_33)
        self.pushButton_y5_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_34.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_34.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_34.setObjectName("pushButton_y5_34")
        self.horizontalLayout_8.addWidget(self.pushButton_y5_34)
        self.pushButton_y5_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_35.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_35.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_35.setObjectName("pushButton_y5_35")
        self.horizontalLayout_8.addWidget(self.pushButton_y5_35)
        self.pushButton_y5_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y5_36.setMinimumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_36.setMaximumSize(QtCore.QSize(60, 60))
        self.pushButton_y5_36.setObjectName("pushButton_y5_36")
        self.horizontalLayout_8.addWidget(self.pushButton_y5_36)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Уровень 5"))
        MainWindow.setWindowIcon(QtGui.QIcon('иконка.png'))
        self.pushButton_vosvrat.setText(_translate("MainWindow", "Вернуться назад"))
        self.pushButton_y5_1.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_2.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_3.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_4.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_5.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_6.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_7.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_8.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_9.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_10.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_11.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_12.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_13.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_14.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_15.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_16.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_17.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_18.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_19.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_20.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_21.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_22.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_23.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_24.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_25.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_26.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_27.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_28.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_29.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_30.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_31.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_32.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_33.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_34.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_35.setText(_translate("MainWindow", "X"))
        self.pushButton_y5_36.setText(_translate("MainWindow", "X"))

        self.pushButton_vosvrat.setStyleSheet('QPushButton {background-color: #EEE8AA;}')
        self.pushButton_y5_1.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_2.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_3.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_4.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_5.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_6.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_7.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_8.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_9.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_10.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_11.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_12.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_13.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_14.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_15.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_16.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_17.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_18.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_19.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_20.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_21.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_22.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_23.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_24.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_25.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_26.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_27.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_28.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_29.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_30.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_31.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_32.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_33.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_34.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_35.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y5_36.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')

