# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uroven_6.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_uroven_6(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        MainWindow.setMinimumSize(QtCore.QSize(450, 500))
        MainWindow.setMaximumSize(QtCore.QSize(450, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_vosvrat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vosvrat.setObjectName("pushButton_vosvrat")
        self.verticalLayout.addWidget(self.pushButton_vosvrat)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_y6_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_1.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_1.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_1.setObjectName("pushButton_y6_1")
        self.horizontalLayout.addWidget(self.pushButton_y6_1)
        self.pushButton_y6_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_2.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_2.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_2.setObjectName("pushButton_y6_2")
        self.horizontalLayout.addWidget(self.pushButton_y6_2)
        self.pushButton_y6_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_3.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_3.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_3.setObjectName("pushButton_y6_3")
        self.horizontalLayout.addWidget(self.pushButton_y6_3)
        self.pushButton_y6_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_4.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_4.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_4.setObjectName("pushButton_y6_4")
        self.horizontalLayout.addWidget(self.pushButton_y6_4)
        self.pushButton_y6_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_5.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_5.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_5.setObjectName("pushButton_y6_5")
        self.horizontalLayout.addWidget(self.pushButton_y6_5)
        self.pushButton_y6_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_6.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_6.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_6.setObjectName("pushButton_y6_6")
        self.horizontalLayout.addWidget(self.pushButton_y6_6)
        self.pushButton_y6_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_7.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_7.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_7.setObjectName("pushButton_y6_7")
        self.horizontalLayout.addWidget(self.pushButton_y6_7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_y6_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_8.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_8.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_8.setObjectName("pushButton_y6_8")
        self.horizontalLayout_2.addWidget(self.pushButton_y6_8)
        self.pushButton_y6_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_9.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_9.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_9.setObjectName("pushButton_y6_9")
        self.horizontalLayout_2.addWidget(self.pushButton_y6_9)
        self.pushButton_y6_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_10.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_10.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_10.setObjectName("pushButton_y6_10")
        self.horizontalLayout_2.addWidget(self.pushButton_y6_10)
        self.pushButton_y6_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_11.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_11.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_11.setObjectName("pushButton_y6_11")
        self.horizontalLayout_2.addWidget(self.pushButton_y6_11)
        self.pushButton_y6_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_12.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_12.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_12.setObjectName("pushButton_y6_12")
        self.horizontalLayout_2.addWidget(self.pushButton_y6_12)
        self.pushButton_y6_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_13.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_13.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_13.setObjectName("pushButton_y6_13")
        self.horizontalLayout_2.addWidget(self.pushButton_y6_13)
        self.pushButton_y6_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_14.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_14.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_14.setObjectName("pushButton_y6_14")
        self.horizontalLayout_2.addWidget(self.pushButton_y6_14)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_y6_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_15.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_15.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_15.setObjectName("pushButton_y6_15")
        self.horizontalLayout_3.addWidget(self.pushButton_y6_15)
        self.pushButton_y6_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_16.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_16.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_16.setObjectName("pushButton_y6_16")
        self.horizontalLayout_3.addWidget(self.pushButton_y6_16)
        self.pushButton_y6_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_17.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_17.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_17.setObjectName("pushButton_y6_17")
        self.horizontalLayout_3.addWidget(self.pushButton_y6_17)
        self.pushButton_y6_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_18.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_18.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_18.setObjectName("pushButton_y6_18")
        self.horizontalLayout_3.addWidget(self.pushButton_y6_18)
        self.pushButton_y6_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_19.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_19.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_19.setObjectName("pushButton_y6_19")
        self.horizontalLayout_3.addWidget(self.pushButton_y6_19)
        self.pushButton_y6_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_20.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_20.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_20.setObjectName("pushButton_y6_20")
        self.horizontalLayout_3.addWidget(self.pushButton_y6_20)
        self.pushButton_y6_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_21.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_21.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_21.setObjectName("pushButton_y6_21")
        self.horizontalLayout_3.addWidget(self.pushButton_y6_21)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_y6_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_22.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_22.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_22.setObjectName("pushButton_y6_22")
        self.horizontalLayout_4.addWidget(self.pushButton_y6_22)
        self.pushButton_y6_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_23.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_23.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_23.setObjectName("pushButton_y6_23")
        self.horizontalLayout_4.addWidget(self.pushButton_y6_23)
        self.pushButton_y6_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_24.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_24.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_24.setObjectName("pushButton_y6_24")
        self.horizontalLayout_4.addWidget(self.pushButton_y6_24)
        self.pushButton_y6_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_25.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_25.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_25.setObjectName("pushButton_y6_25")
        self.horizontalLayout_4.addWidget(self.pushButton_y6_25)
        self.pushButton_y6_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_26.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_26.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_26.setObjectName("pushButton_y6_26")
        self.horizontalLayout_4.addWidget(self.pushButton_y6_26)
        self.pushButton_y6_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_27.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_27.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_27.setObjectName("pushButton_y6_27")
        self.horizontalLayout_4.addWidget(self.pushButton_y6_27)
        self.pushButton_y6_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_28.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_28.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_28.setObjectName("pushButton_y6_28")
        self.horizontalLayout_4.addWidget(self.pushButton_y6_28)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_y6_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_29.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_29.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_29.setObjectName("pushButton_y6_29")
        self.horizontalLayout_5.addWidget(self.pushButton_y6_29)
        self.pushButton_y6_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_30.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_30.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_30.setObjectName("pushButton_y6_30")
        self.horizontalLayout_5.addWidget(self.pushButton_y6_30)
        self.pushButton_y6_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_31.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_31.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_31.setObjectName("pushButton_y6_31")
        self.horizontalLayout_5.addWidget(self.pushButton_y6_31)
        self.pushButton_y6_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_32.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_32.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_32.setObjectName("pushButton_y6_32")
        self.horizontalLayout_5.addWidget(self.pushButton_y6_32)
        self.pushButton_y6_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_33.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_33.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_33.setObjectName("pushButton_y6_33")
        self.horizontalLayout_5.addWidget(self.pushButton_y6_33)
        self.pushButton_y6_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_34.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_34.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_34.setObjectName("pushButton_y6_34")
        self.horizontalLayout_5.addWidget(self.pushButton_y6_34)
        self.pushButton_y6_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_35.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_35.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_35.setObjectName("pushButton_y6_35")
        self.horizontalLayout_5.addWidget(self.pushButton_y6_35)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_y6_36 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_36.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_36.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_36.setObjectName("pushButton_y6_36")
        self.horizontalLayout_6.addWidget(self.pushButton_y6_36)
        self.pushButton_y6_37 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_37.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_37.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_37.setObjectName("pushButton_y6_37")
        self.horizontalLayout_6.addWidget(self.pushButton_y6_37)
        self.pushButton_y6_38 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_38.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_38.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_38.setObjectName("pushButton_y6_38")
        self.horizontalLayout_6.addWidget(self.pushButton_y6_38)
        self.pushButton_y6_39 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_39.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_39.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_39.setObjectName("pushButton_y6_39")
        self.horizontalLayout_6.addWidget(self.pushButton_y6_39)
        self.pushButton_y6_40 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_40.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_40.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_40.setObjectName("pushButton_y6_40")
        self.horizontalLayout_6.addWidget(self.pushButton_y6_40)
        self.pushButton_y6_41 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_41.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_41.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_41.setObjectName("pushButton_y6_41")
        self.horizontalLayout_6.addWidget(self.pushButton_y6_41)
        self.pushButton_y6_42 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_42.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_42.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_42.setObjectName("pushButton_y6_42")
        self.horizontalLayout_6.addWidget(self.pushButton_y6_42)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_y6_43 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_43.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_43.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_43.setObjectName("pushButton_y6_43")
        self.horizontalLayout_7.addWidget(self.pushButton_y6_43)
        self.pushButton_y6_44 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_44.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_44.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_44.setObjectName("pushButton_y6_44")
        self.horizontalLayout_7.addWidget(self.pushButton_y6_44)
        self.pushButton_y6_45 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_45.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_45.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_45.setObjectName("pushButton_y6_45")
        self.horizontalLayout_7.addWidget(self.pushButton_y6_45)
        self.pushButton_y6_46 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_46.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_46.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_46.setObjectName("pushButton_y6_46")
        self.horizontalLayout_7.addWidget(self.pushButton_y6_46)
        self.pushButton_y6_47 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_47.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_47.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_47.setObjectName("pushButton_y6_47")
        self.horizontalLayout_7.addWidget(self.pushButton_y6_47)
        self.pushButton_y6_48 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_48.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_48.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_48.setObjectName("pushButton_y6_48")
        self.horizontalLayout_7.addWidget(self.pushButton_y6_48)
        self.pushButton_y6_49 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y6_49.setMinimumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_49.setMaximumSize(QtCore.QSize(50, 45))
        self.pushButton_y6_49.setObjectName("pushButton_y6_49")
        self.horizontalLayout_7.addWidget(self.pushButton_y6_49)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Уровень 6"))
        MainWindow.setWindowIcon(QtGui.QIcon('иконка.png'))
        self.pushButton_vosvrat.setText(_translate("MainWindow", "Вернуться назад"))
        self.pushButton_y6_1.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_2.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_3.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_4.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_5.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_6.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_7.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_8.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_9.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_10.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_11.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_12.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_13.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_14.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_15.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_16.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_17.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_18.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_19.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_20.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_21.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_22.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_23.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_24.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_25.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_26.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_27.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_28.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_29.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_30.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_31.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_32.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_33.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_34.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_35.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_36.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_37.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_38.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_39.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_40.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_41.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_42.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_43.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_44.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_45.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_46.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_47.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_48.setText(_translate("MainWindow", "X"))
        self.pushButton_y6_49.setText(_translate("MainWindow", "X"))

        self.pushButton_vosvrat.setStyleSheet('QPushButton {background-color: #EEE8AA;}')
        self.pushButton_y6_1.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_2.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_3.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_4.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_5.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_6.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_7.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_8.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_9.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_10.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_11.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_12.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_13.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_14.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_15.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_16.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_17.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_18.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_19.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_20.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_21.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_22.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_23.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_24.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_25.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_26.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_27.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_28.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_29.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_30.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_31.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_32.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_33.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_34.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_35.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_36.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_37.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_38.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_39.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_40.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_41.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_42.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_43.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_44.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_45.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_46.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_47.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_48.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y6_49.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')

