# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uroven_2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow_uroven_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 500)
        MainWindow.setMinimumSize(QtCore.QSize(450, 500))
        MainWindow.setMaximumSize(QtCore.QSize(450, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_vosvrat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vosvrat.setObjectName("pushButton_vosvrat")
        self.verticalLayout_3.addWidget(self.pushButton_vosvrat)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_y2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_1.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_1.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_1.setObjectName("pushButton_y2_1")
        self.horizontalLayout_2.addWidget(self.pushButton_y2_1)
        self.pushButton_y2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_2.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_2.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_2.setObjectName("pushButton_y2_2")
        self.horizontalLayout_2.addWidget(self.pushButton_y2_2)
        self.pushButton_y2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_3.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_3.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_3.setObjectName("pushButton_y2_3")
        self.horizontalLayout_2.addWidget(self.pushButton_y2_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_y2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_4.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_4.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_4.setObjectName("pushButton_y2_4")
        self.horizontalLayout_4.addWidget(self.pushButton_y2_4)
        self.pushButton_y2_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_5.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_5.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_5.setObjectName("pushButton_y2_5")
        self.horizontalLayout_4.addWidget(self.pushButton_y2_5)
        self.pushButton_y2_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_6.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_6.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_6.setObjectName("pushButton_y2_6")
        self.horizontalLayout_4.addWidget(self.pushButton_y2_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_y2_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_7.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_7.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_7.setObjectName("pushButton_y2_7")
        self.horizontalLayout_5.addWidget(self.pushButton_y2_7)
        self.pushButton_y2_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_8.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_8.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_8.setObjectName("pushButton_y2_8")
        self.horizontalLayout_5.addWidget(self.pushButton_y2_8)
        self.pushButton_y2_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_y2_9.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_9.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton_y2_9.setObjectName("pushButton_y2_9")
        self.horizontalLayout_5.addWidget(self.pushButton_y2_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Уровень 2"))
        MainWindow.setWindowIcon(QtGui.QIcon('иконка.png'))
        self.pushButton_vosvrat.setText(_translate("MainWindow", "Вернуться назад"))
        self.pushButton_y2_1.setText(_translate("MainWindow", "X"))
        self.pushButton_y2_2.setText(_translate("MainWindow", "X"))
        self.pushButton_y2_3.setText(_translate("MainWindow", "X"))
        self.pushButton_y2_4.setText(_translate("MainWindow", "X"))
        self.pushButton_y2_5.setText(_translate("MainWindow", "X"))
        self.pushButton_y2_6.setText(_translate("MainWindow", "X"))
        self.pushButton_y2_7.setText(_translate("MainWindow", "X"))
        self.pushButton_y2_8.setText(_translate("MainWindow", "X"))
        self.pushButton_y2_9.setText(_translate("MainWindow", "X"))

        self.pushButton_vosvrat.setStyleSheet('QPushButton {background-color: #EEE8AA;}')
        self.pushButton_y2_1.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y2_2.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y2_3.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y2_4.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y2_5.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y2_6.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y2_7.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y2_8.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')
        self.pushButton_y2_9.setStyleSheet('QPushButton {background-color: #EEE8AA; border-radius: 15px}')

